# API Adapter - Market
Demo tự động các hàm trong class `Market`.

In [2]:
from vnstock_data.api.market import Market

# Khởi tạo instance
instance = Market(source='VND', symbol='VNM')

### `evaluation()`
Retrieves combined P/E and P/B data for the given duration.

In [3]:
df_evaluation = instance.evaluation()
display(df_evaluation)

                   pe        pb
reportDate
2021-04-12  16.960486  2.528316
2021-04-13  16.899745  2.522304
2021-04-14  17.003249  2.537753
2021-04-15  16.887158  2.520426
2021-04-16  16.772415  2.503300
...               ...       ...
2026-04-03  14.013578  2.019555
2026-04-06  13.939022  2.008692
2026-04-07  13.935969  2.011726
2026-04-08  14.594829  2.106586
2026-04-09  14.429553  2.082701

[1241 rows x 2 columns]

### `pb()`
Retrieves P/B ratio data for the given duration.

In [5]:
df_pb = instance.pb()
display(df_pb)

                  pb
reportDate
2021-04-12  2.528316
2021-04-13  2.522304
2021-04-14  2.537753
2021-04-15  2.520426
2021-04-16  2.503300
...              ...
2026-04-03  2.019555
2026-04-06  2.008692
2026-04-07  2.011726
2026-04-08  2.106586
2026-04-09  2.082701

[1241 rows x 1 columns]

### `pe()`
Retrieves P/E ratio data for the given duration.